# Generated by Django 6.1 on 2026-08-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='company_logos')),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full time'), ('Part-time', 'Part time'), ('Temporary', 'Temporary'), ('Freelance', 'Freelance')], max_length=50)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('skills', models.TextField()),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('experience', models.TextField(max_length=50)),
                ('work_location', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('industry_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.industry')),
            ],
        ),
    ]
