# Generated by Django 6.1 on 2026-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
    ]
